#!/usr/bin/env groovy

pipeline {
    agent any
    
    stages{
        stage('Source CFT Environment Variables') {
            steps {
                echo '-----------------'
                echo 'Source CFT_ENV_VARS'
                sh 'source $HOME/cft-env-vars'
                echo '-----------------'
                echo 'Checking CFT Version'
                sh 'cft -v'
            }
        }
        stage('Create Networks, Firewalls') {
            steps {
                echo '-----------------'
                sh 'printenv'
                echo '-----------------'
                // echo 'cft create networks.yaml firewalls.yaml'
                // sh 'cft create networks.yaml firewalls.yaml'
            }
        }
    }
    post {
        // always {
        //     echo 'This will always run'
        // }
        success {
            echo 'This will run only if successful'
        }
        failure {
            echo 'This will run only if failed'
        }
        // unstable {
        //     echo 'This will run only if the run was marked as unstable'
        // }
        // changed {
        //     echo 'This will run only if the state of the Pipeline has changed'
        //     echo 'For example, if the Pipeline was previously failing but is now successful'
        // }
    }
}