#!/usr/bin/env groovy

pipeline {
    agent any
    
    stages{
        stage('Checkout Repos') {
            steps {
                echo '------------------'
                echo 'Cleaning dirs'
                sh 'rm -rf cft demo'
                echo '------------------'
                echo 'Cloning DM Samples github repo' 
                sh 'git clone https://github.com/sourced/deploymentmanager-samples cft'
                sh 'cd cft && git checkout cloud-foundation && cd ..'
            }
        }
        stage('Checking cft Installation') {
            steps {
                echo '------------------'
                echo 'Checking CFT Version'
                sh 'cft -v'
                echo '------------------'
                echo 'Checking CFT Help'
                sh 'cft -h'
            }
        }
        stage('Create Project') {
            environment {
                CONFIG="project/"
            }
            steps {
                sh '. ~/cft-env-vars && cd cft/community/cloud-foundation && cft apply $CONFIG'
            }
        }
    }
}