#!/usr/bin/env groovy

pipeline {
    agent any
    
    stages{
        stage('Checking cft Installation') {
            steps {
                echo 'Checking CFT Version'
                sh 'cft -h'
            }
        }
        stage('Sourcing Env vars') {
            steps {
                sh 'cp /home/tomcat/cft-env-vars . && . ./cft-env-vars && printenv'
            }
        }
        // stage('Create Project') {
        //     steps {
        //         echo '-----------------'
        //         echo 'Source cft environment variables, running cft'
        //         sh 'cp /home/tomcat/cft-env-vars . && \
        //             . ./cft-env-vars && printenv && \
        //             cft create project.yaml
        //             '
        //     }
        // }
    }
    post {
        always {
            echo 'This will always run'
        }
        success {
            echo 'This will run only if successful'
        }
        failure {
            echo 'This will run only if failed'
        }
    }
}